#ifndef MORPHOLOGYFORMATIMPORTEXPORT_HPP_
#define MORPHOLOGYFORMATIMPORTEXPORT_HPP_

class Input;
class Output;
class Neuron3D;
class ExportOptions;

#define DECLAREIMPORTEXPORTFUNCTIONS(name)		bool Import##name	(Input& rIn,	Neuron3D &nrn, const HintOptions& options); bool ImportRaw##name	(const char* file,	Neuron3D &nrn, const HintOptions& options); bool Export##name	(Output& rOut,	const Neuron3D &nrn, const StyleOptions& options); ValidationResult Validate##name	(Input& rIn, const ValidationOptions& options);



// 3D
DECLAREIMPORTEXPORTFUNCTIONS(Amaral)
DECLAREIMPORTEXPORTFUNCTIONS(AmiraMesh)
DECLAREIMPORTEXPORTFUNCTIONS(ArborVitae)
DECLAREIMPORTEXPORTFUNCTIONS(Douglas3D)
DECLAREIMPORTEXPORTFUNCTIONS(Eutectics)
DECLAREIMPORTEXPORTFUNCTIONS(Genesis)
DECLAREIMPORTEXPORTFUNCTIONS(Glasgow)
DECLAREIMPORTEXPORTFUNCTIONS(GulyasTree)
DECLAREIMPORTEXPORTFUNCTIONS(ImarisHDF)
DECLAREIMPORTEXPORTFUNCTIONS(Inventor)
DECLAREIMPORTEXPORTFUNCTIONS(Korogod)
DECLAREIMPORTEXPORTFUNCTIONS(MaxSim)
DECLAREIMPORTEXPORTFUNCTIONS(NeurolucidaASC)
DECLAREIMPORTEXPORTFUNCTIONS(NeurolucidaASCClassic)
DECLAREIMPORTEXPORTFUNCTIONS(NeurolucidaDAT)
DECLAREIMPORTEXPORTFUNCTIONS(NeurolucidaDATClassic)
DECLAREIMPORTEXPORTFUNCTIONS(NeurolucidaXML)
DECLAREIMPORTEXPORTFUNCTIONS(NeuroML)
DECLAREIMPORTEXPORTFUNCTIONS(NeuronHOC)
DECLAREIMPORTEXPORTFUNCTIONS(NeuroZoom)
DECLAREIMPORTEXPORTFUNCTIONS(Nevin)
DECLAREIMPORTEXPORTFUNCTIONS(NINDS3D)
//DECLAREIMPORTEXPORTFUNCTIONS(OntoMorphXML)
DECLAREIMPORTEXPORTFUNCTIONS(Oxford)
DECLAREIMPORTEXPORTFUNCTIONS(PSICS)
DECLAREIMPORTEXPORTFUNCTIONS(SimpleNeuriteTracer)
DECLAREIMPORTEXPORTFUNCTIONS(SWC)

// 2D
DECLAREIMPORTEXPORTFUNCTIONS(Bannister)
DECLAREIMPORTEXPORTFUNCTIONS(NeuronJ)

// 1D
DECLAREIMPORTEXPORTFUNCTIONS(NINDS1D)
DECLAREIMPORTEXPORTFUNCTIONS(Douglas1D)
DECLAREIMPORTEXPORTFUNCTIONS(GulyasSeg1D)



#endif // MORPHOLOGYFORMATIMPORTEXPORT_HPP_