name: xyz2swc

services:
  xyz1:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - data_volume:/app/data/
    restart: always

  xyz2:
    build: .
    ports:
      - "8002:8001"
    volumes:
      - data_volume:/app/data/
    restart: always

  xyz3:
    build: .
    ports:
      - "8003:8001"
    volumes:
      - data_volume:/app/data/
    restart: always

  xyz4:
    build: .
    ports:
      - "8004:8001"
    volumes:
      - data_volume:/app/data/
    restart: always

  xyz5:
    build: .
    ports:
      - "8006:8001"
    volumes:
      - data_volume:/app/data/
    restart: always

  xyz6:
    build: .
    ports:
      - "8007:8001"
    volumes:
      - data_volume:/app/data/
    restart: always

volumes:
  data_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/dev-xvdb/data/xyz2swc

